version: 2.1
jobs:
  build:
    docker:
        - image: circleci/php:7.3-node-browsers
        - image: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_DB: mysa
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret

    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: composer install -n --prefer-dist
      - run:
          name: php test
          command: vendor/bin/phpunit
