version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      #==========ここから追加==========
      - image: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_DB: larasns
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
      #==========ここまで追加==========
    #==========ここから追加==========
    environment:
      APP_ENV: testing
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: larasns
      DB_USERNAME: default
      DB_PASSWORD: secret
    #==========ここまで追加==========
    steps:
      # 略
      - run: npm run dev
      #==========ここから追加==========
      - run:
          name: get ready for postgres
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_pgsql
            dockerize -wait tcp://localhost:5432 -timeout 1m
      #==========ここまで追加==========
      - run:
          name: php test
          command: vendor/bin/phpunit
